### ISSUE TITLE
tiny parser bug

### ISSUE THREAD

**Issue by dncex** [tjko/TinyTZ#1]
Hello,
testing with this posix string "CET-1CEST,M3.5.0,M10.5.0/3", I have the correct result with the "full parser"(function __tzset_parse_tz):
TZ: 0:CET,3600,2,3,5,0,7200
TZ: 1:CEST,7200,2,10,5,0,10800

while with the tiny one (function __parse_TZ_string), the second rule is all zero:
TZ: 0:CET,-3600,2,3,5,0,0
TZ: 1:CEST,0,0,0,0,0,0

**Comment by tjko** [comment]
Is that a valid POSIX timezone?  It would seem to be missing the start time for "CET"...

Following should work ok?
```
CET-1CEST,M3.5.0/3,M10.5.0/3
```

Maybe if start time is not specified default is 2am (02:00)?   Since the result from the "full parser" doesn't seem right either, or daylight savings time start/end are at different times in the morning (2am vs 3am)?

**Comment by tjko** [comment]
I made change to default to 2am (02:00) if the start time is not specified in the TZ string: d6e47808beeca615df8a5d429c9a97a4626cf82e

Does it seem to now work correctly?
